//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulingApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulingApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add appointment..
        /// </summary>
        internal static string ApptAddError {
            get {
                return ResourceManager.GetString("ApptAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments must be scheduled Monday–Friday, 9:00 AM–5:00 PM Eastern Time..
        /// </summary>
        internal static string ApptBusinessHoursError {
            get {
                return ResourceManager.GetString("ApptBusinessHoursError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected appointment?.
        /// </summary>
        internal static string ApptDeleteConfirm {
            get {
                return ResourceManager.GetString("ApptDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete appointment..
        /// </summary>
        internal static string ApptDeleteError {
            get {
                return ResourceManager.GetString("ApptDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This appointment overlaps an existing appointment..
        /// </summary>
        internal static string ApptOverlapError {
            get {
                return ResourceManager.GetString("ApptOverlapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment type is required..
        /// </summary>
        internal static string ApptTypeRequired {
            get {
                return ResourceManager.GetString("ApptTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update appointment..
        /// </summary>
        internal static string ApptUpdateError {
            get {
                return ResourceManager.GetString("ApptUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments for: {0}.
        /// </summary>
        internal static string CalendarForDateLabel {
            get {
                return ResourceManager.GetString("CalendarForDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load calendar appointments..
        /// </summary>
        internal static string CalendarLoadError {
            get {
                return ResourceManager.GetString("CalendarLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add customer..
        /// </summary>
        internal static string CustomerAddError {
            get {
                return ResourceManager.GetString("CustomerAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityId must be a valid positive number..
        /// </summary>
        internal static string CustomerCityIdInvalid {
            get {
                return ResourceManager.GetString("CustomerCityIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete customer &apos;{0}&apos;?.
        /// </summary>
        internal static string CustomerDeleteConfirm {
            get {
                return ResourceManager.GetString("CustomerDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete customer. They may have appointments..
        /// </summary>
        internal static string CustomerDeleteErrorHasAppts {
            get {
                return ResourceManager.GetString("CustomerDeleteErrorHasAppts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update customer..
        /// </summary>
        internal static string CustomerUpdateError {
            get {
                return ResourceManager.GetString("CustomerUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the database..
        /// </summary>
        internal static string LoginDBError {
            get {
                return ResourceManager.GetString("LoginDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string LoginInvalid {
            get {
                return ResourceManager.GetString("LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username and password..
        /// </summary>
        internal static string LoginMissingFields {
            get {
                return ResourceManager.GetString("LoginMissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load appointments..
        /// </summary>
        internal static string MainLoadAppointmentsError {
            get {
                return ResourceManager.GetString("MainLoadAppointmentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Customers.
        /// </summary>
        internal static string MainLoadCustomersError {
            get {
                return ResourceManager.GetString("MainLoadCustomersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load users..
        /// </summary>
        internal static string MainLoadUsersError {
            get {
                return ResourceManager.GetString("MainLoadUsersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no appointments within the next 15 minutes..
        /// </summary>
        internal static string UpcomingApptNo {
            get {
                return ResourceManager.GetString("UpcomingApptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an appointment within 15 minutes. Start: {0}.
        /// </summary>
        internal static string UpcomingApptYes {
            get {
                return ResourceManager.GetString("UpcomingApptYes", resourceCulture);
            }
        }
    }
}
